# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e21a0cd984527ea8703a7cef0dcdfa497207afbd507f6de3cc0616a9c2ed31551bfee443f109e9dc9859359f07094a5eb7036e266373dd1ed83a3cfdf1469655

test:
  secret_key_base: 23a92ad5717acfaa7c79a670daf0a58fce1c33ccd4d521bff27a87bda4bc141a3d2703141c676266e1e54b7bac8c8db03c63d06e3a16c16201d317ea561ccd1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
